server:
  port: 9003

 

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8581/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

 

spring:
  application:
    name: admin-microservice

 

logging:
  level:
    com.example.admin: DEBUG